#!/usr/bin/env python3
"""
STL-to-audio recovery for this vinyl record generator.

Reads binary or ASCII STL geometry produced by the record generator and
reconstructs the encoded audio waveform from the groove geometry.

The tool supports:
  - 7", 10", 12" record sizes
  - 33, 45, 78 RPM groove geometry
  - stereo / mono grooves
  - custom groove spacing factors generated by the existing program
  - side-A / side-B grooves, including combined two-sided STL files
"""

from __future__ import annotations

import argparse
import collections
import math
import os
import statistics
import struct
import sys
import wave
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Tuple

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from record_specs import (
    GROOVE_PTS_PER_REV,
    GROOVE_SAMPLE_RATE,
    MAX_DISPLACEMENT_FRACTION,
    RECORD_SPECS,
    RPM_GROOVE,
    STEREO_45_SCALE,
)

Point3 = Tuple[float, float, float]
Triangle = Tuple[Point3, Point3, Point3]


def is_ascii_stl(data: bytes) -> bool:
    header = data[:80]
    if header.lstrip().lower().startswith(b"solid"):
        if b"facet" in data[:1024].lower():
            return True
    return False


def parse_binary_stl(data: bytes) -> List[Point3]:
    if len(data) < 84:
        raise ValueError("Binary STL too small")
    count = struct.unpack_from("<I", data, 80)[0]
    expected = 84 + count * 50
    if len(data) < expected:
        raise ValueError("Binary STL truncated or malformed")
    verts: List[Point3] = []
    offset = 84
    for _ in range(count):
        # Skip normal vector
        offset += 12
        x0, y0, z0 = struct.unpack_from("<fff", data, offset)
        offset += 12
        x1, y1, z1 = struct.unpack_from("<fff", data, offset)
        offset += 12
        x2, y2, z2 = struct.unpack_from("<fff", data, offset)
        offset += 12
        verts.extend([(x0, y0, z0), (x1, y1, z1), (x2, y2, z2)])
        offset += 2
    return verts


def parse_binary_stl_triangles(data: bytes) -> List[Triangle]:
    if len(data) < 84:
        raise ValueError("Binary STL too small")
    count = struct.unpack_from("<I", data, 80)[0]
    expected = 84 + count * 50
    if len(data) < expected:
        raise ValueError("Binary STL truncated or malformed")
    triangles: List[Triangle] = []
    offset = 84
    for _ in range(count):
        # Skip normal vector
        offset += 12
        x0, y0, z0 = struct.unpack_from("<fff", data, offset)
        offset += 12
        x1, y1, z1 = struct.unpack_from("<fff", data, offset)
        offset += 12
        x2, y2, z2 = struct.unpack_from("<fff", data, offset)
        offset += 12
        triangles.append(((x0, y0, z0), (x1, y1, z1), (x2, y2, z2)))
        offset += 2
    return triangles


def parse_ascii_stl(data: str) -> List[Point3]:
    verts: List[Point3] = []
    for line in data.splitlines():
        line = line.strip()
        if line.startswith("vertex"):
            parts = line.split()
            if len(parts) == 4:
                verts.append((float(parts[1]), float(parts[2]), float(parts[3])))
    return verts


def parse_ascii_stl_triangles(data: str) -> List[Triangle]:
    triangles: List[Triangle] = []
    vertices: List[Point3] = []
    for line in data.splitlines():
        line = line.strip()
        if line.startswith("vertex"):
            parts = line.split()
            if len(parts) == 4:
                vertices.append((float(parts[1]), float(parts[2]), float(parts[3])))
                if len(vertices) == 3:
                    triangles.append((vertices[0], vertices[1], vertices[2]))
                    vertices = []
    return triangles


def load_stl_vertices(path: Path) -> List[Point3]:
    raw = path.read_bytes()
    if is_ascii_stl(raw):
        return parse_ascii_stl(raw.decode("utf-8", errors="ignore"))
    return parse_binary_stl(raw)


def load_stl_mesh(path: Path) -> List[Triangle]:
    raw = path.read_bytes()
    if is_ascii_stl(raw):
        return parse_ascii_stl_triangles(raw.decode("utf-8", errors="ignore"))
    return parse_binary_stl_triangles(raw)


def load_3mf_mesh(path: Path) -> List[Triangle]:
    with zipfile.ZipFile(path, "r") as zf:
        model_name = "3D/3dmodel.model"
        if model_name not in zf.namelist():
            raise ValueError(f"3MF does not contain {model_name}")
        xml_text = zf.read(model_name).decode("utf-8")

    root = ET.fromstring(xml_text)
    namespace = {"m": "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"}
    mesh = root.find(".//m:mesh", namespace)
    if mesh is None:
        raise ValueError("3MF model does not contain mesh data")

    vertices_el = mesh.find("m:vertices", namespace)
    triangles_el = mesh.find("m:triangles", namespace)
    if vertices_el is None or triangles_el is None:
        raise ValueError("Invalid 3MF mesh structure")

    vertices: List[Point3] = []
    for vertex in vertices_el.findall("m:vertex", namespace):
        vertices.append((
            float(vertex.attrib["x"]),
            float(vertex.attrib["y"]),
            float(vertex.attrib["z"]),
        ))

    triangles: List[Triangle] = []
    for triangle in triangles_el.findall("m:triangle", namespace):
        v1 = int(triangle.attrib["v1"])
        v2 = int(triangle.attrib["v2"])
        v3 = int(triangle.attrib["v3"])
        triangles.append((vertices[v1], vertices[v2], vertices[v3]))
    return triangles


def load_geometry(path: Path) -> tuple[List[Point3], List[Triangle]]:
    suffix = path.suffix.lower()
    if suffix == ".stl":
        triangles = load_stl_mesh(path)
    elif suffix == ".3mf":
        triangles = load_3mf_mesh(path)
    else:
        raise ValueError("Unsupported geometry format: only .stl and .3mf are supported")

    vertices = unique_vertices(pt for tri in triangles for pt in tri)
    return vertices, triangles


def round_pt(pt: Point3, ndigits: int = 5) -> Point3:
    return (round(pt[0], ndigits), round(pt[1], ndigits), round(pt[2], ndigits))


def unique_vertices(points: Iterable[Point3], ndigits: int = 5) -> List[Point3]:
    seen = set()
    unique: List[Point3] = []
    for pt in points:
        r = round_pt(pt, ndigits)
        if r not in seen:
            seen.add(r)
            unique.append(r)
    return unique


def radius(pt: Point3) -> float:
    return math.hypot(pt[0], pt[1])


def side_top_z_candidates(points: Sequence[Point3]) -> List[float]:
    z_counts = collections.Counter(round(pt[2], 3) for pt in points)
    min_z = min(z_counts)
    peaks = [z for z, count in z_counts.items() if count >= 400 and z > min_z + 0.5]
    peaks.sort(reverse=True)
    if not peaks:
        # Fallback: use max z only
        return [max(pt[2] for pt in points)]
    grouped: List[float] = []
    for z in peaks:
        if not grouped or abs(z - grouped[-1]) > 0.5:
            grouped.append(z)
    return grouped[:2]


def side_vertices_by_top_z(points: Sequence[Point3]) -> List[Tuple[float, List[Point3]]]:
    tops = side_top_z_candidates(points)
    sections: List[Tuple[float, List[Point3]]] = []
    for top_z in tops:
        # Cut out the side using a height range slightly larger than thickness.
        side_points = [pt for pt in points if pt[2] >= top_z - 2.5 and pt[2] <= top_z + 0.01]
        if side_points:
            sections.append((top_z, unique_vertices(side_points, ndigits=5)))
    if not sections:
        raise ValueError("Unable to isolate record side from STL geometry")
    return sections


def side_triangles_by_top_z(triangles: Sequence[Triangle]) -> List[Tuple[float, List[Triangle]]]:
    points = [pt for tri in triangles for pt in tri]
    tops = side_top_z_candidates(points)
    sections: List[Tuple[float, List[Triangle]]] = []
    for top_z in tops:
        side_tris: List[Triangle] = []
        for tri in triangles:
            avg_z = sum(pt[2] for pt in tri) / 3.0
            if top_z - 2.5 <= avg_z <= top_z + 0.01:
                side_tris.append(tri)
        if side_tris:
            sections.append((top_z, side_tris))
    if not sections:
        raise ValueError("Unable to isolate record side from 3D geometry")
    return sections


def choose_size_inch(r_outer: float) -> int:
    best = min(RECORD_SPECS.items(), key=lambda x: abs(x[1]["outer_r"] - r_outer))
    return best[0]


def unwrap_angles(points: List[Point3]) -> List[float]:
    angles = [math.atan2(y, x) for x, y, _ in points]
    unwrapped: List[float] = []
    for a in angles:
        if not unwrapped:
            unwrapped.append(a)
            continue
        prev = unwrapped[-1]
        delta = a - prev
        if delta > math.pi:
            delta -= 2 * math.pi
        elif delta < -math.pi:
            delta += 2 * math.pi
        unwrapped.append(prev + delta)
    return unwrapped


def sort_spiral_points(points: Sequence[Point3]) -> List[Point3]:
    def spiral_angle(pt: Point3) -> float:
        angle = math.atan2(pt[1], pt[0])
        return angle if angle >= 0 else angle + 2.0 * math.pi

    ordered = sorted(points, key=lambda pt: (-radius(pt), spiral_angle(pt)))
    return ordered


def smooth_track_radii(radii: Sequence[float], window: int = 101) -> List[float]:
    n = len(radii)
    if n == 0:
        return []
    window = max(3, min(window, n))
    half = window // 2
    smoothed: List[float] = []
    for i in range(n):
        lo = max(0, i - half)
        hi = min(n, i + half + 1)
        smoothed.append(statistics.median(radii[lo:hi]))
    return smoothed


def extract_floor_points(points: Sequence[Point3], top_z: float, groove_depth: float) -> List[Point3]:
    if not points:
        return []
    min_z = min(pt[2] for pt in points)
    threshold = min_z + max(0.02, min(groove_depth * 0.55, (top_z - min_z) * 0.6))
    floor_points = [pt for pt in points if pt[2] <= threshold]
    if len(floor_points) < max(32, len(points) // 8):
        return list(points)
    return unique_vertices(floor_points, ndigits=5)


def infer_size_rpm_quality(points: Sequence[Point3], size_inch: int) -> Tuple[int, str, float, float]:
    if not points:
        raise ValueError("No groove points to infer record parameters")

    ordered = sort_spiral_points(points)
    angles = unwrap_angles(ordered)
    total_angle = abs(angles[-1] - angles[0])
    total_revs = total_angle / (2.0 * math.pi)
    total_pts = len(ordered)
    if total_revs < 0.1:
        raise ValueError("Insufficient spiral revolutions detected")

    points_per_rev = total_pts / total_revs
    best_quality = min(
        GROOVE_PTS_PER_REV.items(),
        key=lambda item: abs(item[1] - points_per_rev),
    )[0]
    pts_per_rev = GROOVE_PTS_PER_REV[best_quality]

    spec = RECORD_SPECS[size_inch]
    r_out = spec["groove_outer_r"]
    r_in = spec["groove_inner_r"]
    pitch = (r_out - r_in) / total_revs

    candidate: Optional[Tuple[int, str, float]] = None
    best_error = float("inf")
    for rpm, groove in RPM_GROOVE.items():
        width = groove["groove_width"]
        spacing = groove["groove_spacing"]
        factor = (pitch - width) / spacing
        if factor < 0.4 or factor > 2.2:
            continue
        expected_pitch = width + spacing * factor
        error = abs(expected_pitch - pitch)
        if error < best_error:
            best_error = error
            candidate = (rpm, best_quality, factor)

    if candidate is None:
        candidate = (33, best_quality, 1.0)
    return candidate[0], candidate[1], candidate[2], pitch


def is_stereo(points: Sequence[Point3], top_z: float, thickness: float, groove_depth: float) -> bool:
    floors = [pt for pt in points if pt[2] <= top_z - 0.08 and pt[2] >= top_z - thickness - 0.05]
    if len(floors) < 3:
        return False
    depths = [top_z - groove_depth - pt[2] for pt in floors]
    return max(depths) - min(depths) > 0.005


def reconstruct_waveform(
    points: Sequence[Point3],
    size_inch: int,
    rpm: int,
    quality: str,
    groove_spacing_factor: float,
    side: str,
    apply_inverse_riaa: bool = False,
) -> Tuple[List[float], List[float], int, bool]:
    spec = RECORD_SPECS[size_inch]
    groove = RPM_GROOVE[rpm]
    thickness = spec["thickness"]
    groove_depth = groove["groove_depth"]
    half_w = groove["groove_width"] / 2.0
    max_disp = half_w * MAX_DISPLACEMENT_FRACTION
    sample_rate = GROOVE_SAMPLE_RATE

    top_z = max(pt[2] for pt in points)
    floor_points = extract_floor_points(points, top_z, groove_depth)
    ordered = sort_spiral_points(floor_points)
    if len(ordered) < 16:
        ordered = sort_spiral_points(points)
    angles = unwrap_angles(ordered)
    total_angle = angles[-1] - angles[0]
    total_revs = abs(total_angle) / (2.0 * math.pi)
    pts_per_rev = GROOVE_PTS_PER_REV[quality]
    samples_per_point = sample_rate * 60.0 / rpm / pts_per_rev

    nominal_floor = thickness - groove_depth
    radii = [radius(pt) for pt in ordered]
    track_radii = smooth_track_radii(radii, window=max(11, pts_per_rev // 4))

    is_stereo_mode = is_stereo(points, max(pt[2] for pt in points), thickness, groove_depth)
    n_samples = int(math.ceil(len(ordered) * samples_per_point))
    left = [0.0] * n_samples
    right = [0.0] * n_samples
    filled = [False] * n_samples

    for idx, (x, y, z) in enumerate(ordered):
        angle = angles[idx]
        cos_a = math.cos(angle)
        sin_a = math.sin(angle)
        d_lat = (x * cos_a + y * sin_a) - track_radii[idx]
        d_vert = z - nominal_floor

        if is_stereo_mode:
            norm_lat = d_lat / max_disp / STEREO_45_SCALE
            norm_vert = d_vert / (groove_depth * 0.35) / STEREO_45_SCALE
            l = (norm_lat + norm_vert) * 0.5
            r = (norm_lat - norm_vert) * 0.5
        else:
            norm_lat = d_lat / max_disp
            l = r = norm_lat

        l = max(-1.0, min(1.0, l))
        r = max(-1.0, min(1.0, r))

        sample_index = min(int(idx * samples_per_point), n_samples - 1)
        left[sample_index] = l
        right[sample_index] = r
        filled[sample_index] = True

    # Fill gaps using last seen value
    last_l = left[0]
    last_r = right[0]
    for i in range(n_samples):
        if filled[i]:
            last_l = left[i]
            last_r = right[i]
        else:
            left[i] = last_l
            right[i] = last_r

    if side.upper() == "B":
        left.reverse()
        right.reverse()

    if apply_inverse_riaa:
        left = inverse_riaa(left, sample_rate)
        right = inverse_riaa(right, sample_rate)

    return left, right, sample_rate, is_stereo_mode


def write_wav(path: Path, left: List[float], right: List[float], sample_rate: int) -> None:
    stereo = len(left) == len(right) and any(abs(l - r) > 1e-9 for l, r in zip(left, right))
    channels = 2 if stereo else 1
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(channels)
        wf.setsampwidth(2)
        wf.setframerate(sample_rate)
        for i in range(len(left)):
            if stereo:
                wf.writeframes(struct.pack("<hh", int(32767 * max(-1.0, min(1.0, left[i]))), int(32767 * max(-1.0, min(1.0, right[i])))))
            else:
                wf.writeframes(struct.pack("<h", int(32767 * max(-1.0, min(1.0, left[i])))))


def write_3mf(path: Path, triangles: List[Triangle]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    model_ns = "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"

    def ns(tag: str) -> str:
        return f"{{{model_ns}}}{tag}"

    model = ET.Element(ns("model"), xmlns=model_ns)
    model.set("unit", "millimeter")
    resources = ET.SubElement(model, ns("resources"))
    obj = ET.SubElement(resources, ns("object"), id="1", type="model")
    mesh = ET.SubElement(obj, ns("mesh"))
    vertices_el = ET.SubElement(mesh, ns("vertices"))

    unique_vertices: List[Point3] = []
    index_map: dict[Point3, int] = {}
    for tri in triangles:
        for pt in tri:
            if pt not in index_map:
                index_map[pt] = len(unique_vertices)
                unique_vertices.append(pt)

    for x, y, z in unique_vertices:
        ET.SubElement(vertices_el, ns("vertex"), x=str(x), y=str(y), z=str(z))

    triangles_el = ET.SubElement(mesh, ns("triangles"))
    for v0, v1, v2 in triangles:
        ET.SubElement(
            triangles_el,
            ns("triangle"),
            v1=str(index_map[v0]),
            v2=str(index_map[v1]),
            v3=str(index_map[v2]),
        )

    build = ET.SubElement(model, ns("build"))
    ET.SubElement(build, ns("item"), objectid="1")

    model_bytes = ET.tostring(model, encoding="utf-8", xml_declaration=True)

    content_types = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>'
        '</Types>'
    )
    rels = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/relationship/3dmodel" Target="/3D/3dmodel.model"/>'
        '</Relationships>'
    )

    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("3D/3dmodel.model", model_bytes)


class RIAAInverse:
    def __init__(self, sample_rate: int):
        self.sample_rate = sample_rate
        self._compute_coeffs()
        self._z1 = 0.0
        self._z2 = 0.0

    def _compute_coeffs(self):
        sr = self.sample_rate
        T = 1.0 / sr
        w1 = 1.0 / 3180.0
        w2 = 1.0 / 318.0
        w3 = 1.0 / 75.0
        w1d = 2.0 * sr * math.tan(w1 * T / 2.0)
        w2d = 2.0 * sr * math.tan(w2 * T / 2.0)
        w3d = 2.0 * sr * math.tan(w3 * T / 2.0)
        k1 = w1d / (2.0 * sr)
        k2 = w2d / (2.0 * sr)
        k3 = w3d / (2.0 * sr)
        self.a1 = (1.0 - k2) / (1.0 + k2)
        self.b0 = (1.0 + k1 + k3 + k1 * k3) / (1.0 + k2)
        self.b1 = (2.0 - 2.0 * k1 * k3) / (1.0 + k2)
        self.b2 = (1.0 - k1 - k3 + k1 * k3) / (1.0 + k2)

    def process(self, samples: List[float]) -> List[float]:
        out: List[float] = []
        x1 = x2 = 0.0
        y1 = y2 = 0.0
        for x in samples:
            y = self.b0 * x + self.b1 * x1 + self.b2 * x2 - self.a1 * y1
            out.append(y)
            x2, x1 = x1, x
            y2, y1 = y1, y
        return out


def inverse_riaa(samples: List[float], sample_rate: int) -> List[float]:
    return RIAAInverse(sample_rate).process(samples)


def describe_inference(size_inch: int, rpm: int, quality: str, factor: float, is_stereo: bool) -> str:
    return (
        f"Detected record: {size_inch}\" {rpm} RPM, quality={quality}, "
        f"groove_spacing_factor={factor:.2f}, groove_type={'stereo' if is_stereo else 'mono'}"
    )


def output_file_for_side(base: Path, side: str, stereo: bool) -> Path:
    suffix = "_sideA" if side.upper() == "A" else "_sideB"
    ext = ".wav"
    return base.with_name(base.stem + suffix + ext) if stereo or side else base.with_suffix(ext)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Recover audio WAV and optional 3MF from record geometry produced by this project."
    )
    parser.add_argument("input", help="STL or 3MF file, or folder containing STL/3MF files")
    parser.add_argument("--output-dir", help="Directory for recovered files", default="reverse_record_output")
    parser.add_argument("--output-format", choices=["wav", "3mf", "both"], default="wav",
                        help="Output format for recovered files")
    parser.add_argument("--side", choices=["A", "B", "auto"], default="auto",
                        help="Assume Side A or Side B when input contains a single side")
    parser.add_argument("--inverse-riaa", action="store_true",
                        help="Apply inverse RIAA playback equalisation to recovered audio")
    args = parser.parse_args()

    path = Path(args.input)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files: List[Path] = []
    if path.is_dir():
        files = sorted(path.glob("*.stl"))
    else:
        files = [path]

    if not files:
        print("No STL files found to process.")
        return 1

    for stl_path in files:
        print(f"Processing: {stl_path}")
        vertices, triangles = load_geometry(stl_path)
        sides = sorted(side_vertices_by_top_z(vertices), key=lambda item: item[0])
        side_meshes = side_triangles_by_top_z(triangles)
        if len(sides) > 1:
            print(f"  Found {len(sides)} sides in combined geometry file.")
        for idx, ((top_z, side_points), (_, side_triangles)) in enumerate(zip(sides, side_meshes), start=1):
            side_name = "A" if idx == 1 else "B" if len(sides) == 2 else "A"
            if len(sides) == 1 and args.side != "auto":
                side_name = args.side
            r_outer = max(radius(pt) for pt in side_points)
            size_inch = choose_size_inch(r_outer)
            rpm, quality, factor, pitch = infer_size_rpm_quality(side_points, size_inch)
            stereo = is_stereo(side_points, top_z, RECORD_SPECS[size_inch]["thickness"], RPM_GROOVE[rpm]["groove_depth"])
            print(f"  {describe_inference(size_inch, rpm, quality, factor, stereo)}")
            left, right, sample_rate, stereo_flag = reconstruct_waveform(
                side_points,
                size_inch,
                rpm,
                quality,
                factor,
                side_name,
                apply_inverse_riaa=args.inverse_riaa,
            )
            base_name = output_dir / stl_path.stem
            wav_path = base_name.with_name(f"{base_name.stem}_{side_name}.wav") if len(sides) > 1 else base_name.with_suffix(".wav")
            write_wav(wav_path, left, right, sample_rate)
            print(f"  Wrote {wav_path} ({'stereo' if stereo_flag else 'mono'})")
            if args.output_format in ("3mf", "both"):
                mesh_path = base_name.with_name(f"{base_name.stem}_{side_name}.3mf") if len(sides) > 1 else base_name.with_suffix(".3mf")
                write_3mf(mesh_path, side_triangles)
                print(f"  Wrote {mesh_path} (3MF)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
